# ==============================================================================
# Конфигурация Prometheus
# Copyleft(c) by Denis Astahov | Доработка: devcloud13 (https://github.com/devcloud13)
# Оригинал: https://github.com/adv4000/prometheus
# ==============================================================================

global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "ubuntu-servers"
    static_configs:
      - targets:
          - "10.0.0.1:9100"
          - "10.0.0.2:9100"
